### ISSUE TITLE
New sample

### ISSUE THREAD

**Issue by maddybe92** [syspremed/exploBATCH_serial#2]
Hello!
How would you able to add a new sample, for example the bladder eset. 

_you_dont_have to answer. thanks,, :)

**Comment by syspremed** [comment]
You can use your own data with exploBATCH by reading it into R using the basic functions such as `read.delim`. When your data is in a matrix, you can then use it for the `D` argument in `expBATCH`.

If you have issues with basic usage of R, please search for your question on sites such as StackOverflow.
