### ISSUE TITLE
Add another algorithm

### ISSUE THREAD

**Issue by maddybe92** [syspremed/exploBATCH_serial#2]
Hi!
I was wondering how would you be able to add another algorthm to the package? :) BR

**Comment by gnyamundanda** [comment]
Hi Gift

Can you assist with this?

Thanks

Anguraj

**Comment by syspremed** [comment]
You just need to add all the functions associated with that algorithm into the package and call those functions within the main exploBATCH function called expBATCH.R. 

What is the algorithm you want to add?

Thanks,

Gift.

**Comment by syspremed** [comment]
limma and RUV are both good methods for batch corrections. You can add removeBatchEffect function in limma into exploBATCH function and call it in the main code expBATCH.R.

You can make a github pull request and we can see if we can add it in our repo.

Thanks,

Gift.

**Comment by maddybe92** [comment]
Hi! I was thinking gene shift which can be found in insilicomerging, but I don’t have any good link towards it, hence I suggest RUV, sva, limma and Pamr. :) Appreciate any help.

**Comment by syspremed** [comment]
You cannot do that all at once I'm afraid. ComBat is the only function implemented other than PPCCA. If we get more requests to add other methods we will consider including them.

If I am understanding you correctly, if you want to run `limma` batch correction, then check if there is batch effect using `expBATCH`, then you would simply run `removeBatchEffect` first then call `expBATCH` as above. I am not very familiar with `limma` batch correction but it would look something like this:

```
library(limma)
library(exploBATCH)
library(exploBATCHcolon)

data(Colon)
data(batchColon)
data(bioCL)

design <- model.matrix(~factor(bioCL))
ColonLimma <- removeBatchEffect(x = t(Colon), batch = batchColon, design = design)
expBATCH(D = t(ColonLimma), batchCL = batchColon, Conf = bioCL, mindim = 2, maxdim = 9, method = 'ppcca')
```

You can then look in the *findBATCH*, *pcaBeforeCorrection* and *ppccaBeforeCorrection* folders in your working directory to see what the results were from just `limma` batch correction.

I'm going to close this issue for now as the purpose of this package is to implement PPCCA but I hope you are able to find some interesting results from using `limma` etc.

**Comment by maddybe92** [comment]
Hi! The code does not work.

**Comment by maddybe92** [comment]
Is there no way to add an if else function
